/**********************************************************************************************************************
 * \file bootloader.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "bootloader.h"
#include "ota_flash.h"
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
typedef void (*AppFunc)(void);
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
static void Bootloader_JumpToApp(uint32 appAddr)
{
    /* TC375 점프: 앱의 시작 벡터 주소로 점프 */
    AppFunc app = (AppFunc)(*(volatile uint32 *)(appAddr));
    app();
}

void Bootloader_Main(void)
{
    /* 1. DFLASH 플래그 읽기 */
    uint32 flag = *(volatile uint32 *)OTA_FLAG_ADDR;

    if (flag == OTA_FLAG_MAGIC)
    {
        /* 2. Bank B 메타데이터 읽기 (플래그 옆에 저장) */
        uint32 fwSize     = *(volatile uint32 *)(OTA_FLAG_ADDR + 8);
        uint32 expectedCRC = *(volatile uint32 *)(OTA_FLAG_ADDR + 16);


        /* 3. CRC 검증 */
        if (OTA_Flash_VerifyCRC(BANK_B_START, fwSize, expectedCRC))
        {
            /* 4. 검증 성공 → 플래그 클리어 → Bank B 실행 */
            OTA_Flash_ClearFlag();
            Bootloader_JumpToApp(BANK_B_START);
        }
        else
        {
            /* 5. 검증 실패 → 롤백 → Bank A 실행 */
            OTA_Flash_ClearFlag();
            Bootloader_JumpToApp(APP_START_ADDR);
        }
    }
    else
    {
        /* 6. 플래그 없음 → 정상 부팅 → Bank A 실행 */
        Bootloader_JumpToApp(APP_START_ADDR);
    }
}

/*********************************************************************************************************************/
