/**********************************************************************************************************************
 * \file ota_flash.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef OTA_FLASH_H_
#define OTA_FLASH_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Ifx_Types.h"
#include "IfxFlash.h"

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
#define OTA_FLAG_ADDR       0xAF000000UL    /* DFLASH 플래그 저장 위치 */
#define OTA_FLAG_MAGIC      0xDEADBEEFUL   /* OTA 모드 진입 식별값    */

#define BANK_B_START        0x80400000UL    /* 새 FW 기록할 PFLASH Bank B */
#define APP_START_ADDR      0x80020000UL    /* 현재 App FW 시작 주소      */

#define FLASH_MODULE            0
#define PFLASH_PAGE_LEN         32      /* PFLASH 페이지 = 32바이트 (예제와 동일) */
#define DFLASH_PAGE_LEN         8       /* DFLASH 페이지 = 8바이트  (예제와 동일) */
#define PFLASH_SECTOR_SIZE      0x4000  /* PFLASH 섹터 = 16KB */

#define RELOCATION_START_ADDR   0x70100000U
#define ERASESECTOR_LEN         110
#define WAITUNBUSY_LEN          110
#define ENTERPAGEMODE_LEN       110
#define LOADPAGE2X32_LEN        110
#define WRITEPAGE_LEN           110

#define ERASESECTOR_ADDR        (RELOCATION_START_ADDR)
#define WAITUNBUSY_ADDR         (ERASESECTOR_ADDR    + ERASESECTOR_LEN)
#define ENTERPAGEMODE_ADDR      (WAITUNBUSY_ADDR     + WAITUNBUSY_LEN)
#define LOAD2X32_ADDR           (ENTERPAGEMODE_ADDR  + ENTERPAGEMODE_LEN)
#define WRITEPAGE_ADDR          (LOAD2X32_ADDR       + LOADPAGE2X32_LEN)

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
typedef struct
{
    void  (*eraseSectors) (uint32 sectorAddr, uint32 numSector);
    uint8 (*waitUnbusy)   (uint32 flash, IfxFlash_FlashType flashType);
    uint8 (*enterPageMode)(uint32 pageAddr);
    void  (*load2X32bits) (uint32 pageAddr, uint32 wordL, uint32 wordU);
    void  (*writePage)    (uint32 pageAddr);
} OTA_FlashFunc;

/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
void    OTA_Flash_Erase    (uint32 addr, uint32 size);
boolean OTA_Flash_Write    (uint32 addr, uint8 *data, uint16 len);
boolean OTA_Flash_VerifyCRC(uint32 addr, uint32 size, uint32 expectedCRC);
void    OTA_Flash_SetFlag(uint32 fwSize, uint32 expectedCRC);
void    OTA_Flash_ClearFlag(void);

/*********************************************************************************************************************/


#endif /* OTA_FLASH_H_ */
