/**********************************************************************************************************************
 * \file ota_flash.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "ota_flash.h"
#include "IfxFlash.h"
#include "IfxScuWdt.h"
#include "IfxScuRcu.h"
#include <string.h>

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
static OTA_FlashFunc g_func;
static boolean       g_funcCopied = FALSE;

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
static void OTA_CopyFuncsToPSPR(void);

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
static void OTA_CopyFuncsToPSPR(void)
{
    if (g_funcCopied) return;   /* 이미 복사했으면 스킵 */

    memcpy((void *)ERASESECTOR_ADDR,   (const void *)IfxFlash_eraseMultipleSectors, ERASESECTOR_LEN);
    memcpy((void *)WAITUNBUSY_ADDR,    (const void *)IfxFlash_waitUnbusy,           WAITUNBUSY_LEN);
    memcpy((void *)ENTERPAGEMODE_ADDR, (const void *)IfxFlash_enterPageMode,        ENTERPAGEMODE_LEN);
    memcpy((void *)LOAD2X32_ADDR,      (const void *)IfxFlash_loadPage2X32,         LOADPAGE2X32_LEN);
    memcpy((void *)WRITEPAGE_ADDR,     (const void *)IfxFlash_writePage,            WRITEPAGE_LEN);

    g_func.eraseSectors  = (void *)ERASESECTOR_ADDR;
    g_func.waitUnbusy    = (void *)WAITUNBUSY_ADDR;
    g_func.enterPageMode = (void *)ENTERPAGEMODE_ADDR;
    g_func.load2X32bits  = (void *)LOAD2X32_ADDR;
    g_func.writePage     = (void *)WRITEPAGE_ADDR;

    g_funcCopied = TRUE;
}

/* ── PFLASH Erase ───────────────────────────────────────────── */
/* Flash_Programming.c erasePFLASH() 와 동일한 패턴              */
void OTA_Flash_Erase(uint32 addr, uint32 size)
{
    OTA_CopyFuncsToPSPR();

    uint16 pw = IfxScuWdt_getSafetyWatchdogPassword();

    /* 섹터 개수 계산 (올림) */
    uint32 sectorCount = (size + PFLASH_SECTOR_SIZE - 1) / PFLASH_SECTOR_SIZE;
    if (sectorCount == 0) sectorCount = 1;

    IfxScuWdt_clearSafetyEndinitInline(pw);
    g_func.eraseSectors(addr, sectorCount);
    IfxScuWdt_setSafetyEndinitInline(pw);

    g_func.waitUnbusy(FLASH_MODULE, IfxFlash_FlashType_P0);
}

/* ── PFLASH Write ───────────────────────────────────────────── */
/* Flash_Programming.c writePFLASH() 와 동일한 패턴              */
/* 32바이트(1페이지) 단위로 기록                                   */
boolean OTA_Flash_Write(uint32 addr, uint8 *data, uint16 len)
{
    OTA_CopyFuncsToPSPR();

    uint16 pw        = IfxScuWdt_getSafetyWatchdogPassword();
    uint32 writeAddr = addr;
    uint16 offset    = 0;

    /* 32바이트 미만 마지막 청크는 0xFF 패딩 */
    uint8 pageBuf[PFLASH_PAGE_LEN];

    while (offset < len)
    {
        /* 페이지 버퍼 준비 */
        memset(pageBuf, 0xFF, PFLASH_PAGE_LEN);
        uint16 copyLen = len - offset;
        if (copyLen > PFLASH_PAGE_LEN) copyLen = PFLASH_PAGE_LEN;
        memcpy(pageBuf, data + offset, copyLen);

        /* 1. 페이지 모드 진입 (예제와 동일) */
        g_func.enterPageMode(writeAddr);
        g_func.waitUnbusy(FLASH_MODULE, IfxFlash_FlashType_P0);

        /* 2. 어셈블리 버퍼에 32바이트 로드 (8바이트씩 4회) */
        for (uint16 i = 0; i < PFLASH_PAGE_LEN; i += 8)
        {
            uint32 lo = *(uint32 *)(pageBuf + i);
            uint32 hi = *(uint32 *)(pageBuf + i + 4);
            g_func.load2X32bits(writeAddr, lo, hi);
        }

        /* 3. Flash Write (EndInit 보호 해제/복구 필수) */
        IfxScuWdt_clearSafetyEndinitInline(pw);
        g_func.writePage(writeAddr);
        IfxScuWdt_setSafetyEndinitInline(pw);

        g_func.waitUnbusy(FLASH_MODULE, IfxFlash_FlashType_P0);

        writeAddr += PFLASH_PAGE_LEN;
        offset    += copyLen;
    }

    return TRUE;
}

/* ── CRC32 검증 ─────────────────────────────────────────────── */
/* Flash에 기록된 데이터를 읽어서 CRC 계산                         */
boolean OTA_Flash_VerifyCRC(uint32 addr, uint32 size, uint32 expectedCRC)
{
    uint32  crc = 0xFFFFFFFF;
    uint8  *ptr = (uint8 *)addr;

    for (uint32 i = 0; i < size; i++)
    {
        crc ^= ptr[i];
        for (uint8 j = 0; j < 8; j++)
            crc = (crc >> 1) ^ (0xEDB88320UL & (uint32)(-(sint32)(crc & 1)));
    }
    crc ^= 0xFFFFFFFF;

    /*
     * TODO: RPi가 0x37 요청에 예상 CRC를 포함해서 보내도록 확장 시
     *       여기서 expected CRC와 비교.
     *       현재는 계산만 하고 항상 TRUE 반환 (개발 단계)
     */
    (void)crc;
    //return TRUE;
    return (crc == expectedCRC);  // 실제 비교
}

/* ── DFLASH OTA 플래그 기록 ─────────────────────────────────── */
/* Flash_Programming.c writeDataFlash() 와 동일한 패턴            */
void OTA_Flash_SetFlag(uint32 fwSize, uint32 expectedCRC)
{
    uint16 pw = IfxScuWdt_getSafetyWatchdogPassword();

    /* 1. Erase */
    IfxScuWdt_clearSafetyEndinit(pw);
    IfxFlash_eraseMultipleSectors(OTA_FLAG_ADDR, 1);
    IfxScuWdt_setSafetyEndinit(pw);
    IfxFlash_waitUnbusy(FLASH_MODULE, IfxFlash_FlashType_D0);

    /* 2. Write (DFLASH는 PSPR 불필요 — 예제와 동일) */
    /* 2. MAGIC 저장 */
    IfxFlash_enterPageMode(OTA_FLAG_ADDR);
    IfxFlash_waitUnbusy(FLASH_MODULE, IfxFlash_FlashType_D0);
    IfxFlash_loadPage2X32(OTA_FLAG_ADDR, OTA_FLAG_MAGIC, 0x00000000UL);
    IfxScuWdt_clearSafetyEndinit(pw);
    IfxFlash_writePage(OTA_FLAG_ADDR);
    IfxScuWdt_setSafetyEndinit(pw);
    IfxFlash_waitUnbusy(FLASH_MODULE, IfxFlash_FlashType_D0);

    /* 3. fw_size 저장 */
    IfxFlash_enterPageMode(OTA_FLAG_ADDR + 8);
    IfxFlash_waitUnbusy(FLASH_MODULE, IfxFlash_FlashType_D0);
    IfxFlash_loadPage2X32(OTA_FLAG_ADDR + 8, fwSize, 0x00000000UL);
    IfxScuWdt_clearSafetyEndinit(pw);
    IfxFlash_writePage(OTA_FLAG_ADDR + 8);
    IfxScuWdt_setSafetyEndinit(pw);
    IfxFlash_waitUnbusy(FLASH_MODULE, IfxFlash_FlashType_D0);

    /* 4. expectedCRC 저장 */
    IfxFlash_enterPageMode(OTA_FLAG_ADDR + 16);
    IfxFlash_waitUnbusy(FLASH_MODULE, IfxFlash_FlashType_D0);
    IfxFlash_loadPage2X32(OTA_FLAG_ADDR + 16, expectedCRC, 0x00000000UL);
    IfxScuWdt_clearSafetyEndinit(pw);
    IfxFlash_writePage(OTA_FLAG_ADDR + 16);
    IfxScuWdt_setSafetyEndinit(pw);
    IfxFlash_waitUnbusy(FLASH_MODULE, IfxFlash_FlashType_D0);
}

/* ── DFLASH OTA 플래그 클리어 ──────────────────────────────── */
/* Bootloader에서 플래그 확인 후 클리어할 때 사용                  */
void OTA_Flash_ClearFlag(void)
{
    uint16 pw = IfxScuWdt_getSafetyWatchdogPassword();

    IfxScuWdt_clearSafetyEndinit(pw);
    IfxFlash_eraseMultipleSectors(OTA_FLAG_ADDR, 1);
    IfxScuWdt_setSafetyEndinit(pw);
    IfxFlash_waitUnbusy(FLASH_MODULE, IfxFlash_FlashType_D0);
}

/*********************************************************************************************************************/
